////////////////////////////////////////
// Creator: Farhan
// Date: 26-May-2023
// Module: Setting
//////////////////////////////////////

Set the SearchRectangle to "Common/CustomRectangle".ScreenPart("BottomHalf")

Click imageName:"MainPage/ReportIcon", waitFor:15

set the SearchRectangle to "Common/CustomRectangle".ScreenPart("Middle")

put ImageFound(text:"Enter your PIN", waitFor:15) into IsPINFound

Assert that IsPINFound is true


Set the SearchRectangle to empty