////////////////////////////////////////
// Creator: Chan Si Min
// Date: 17-May-2023
// Module: Printer
//////////////////////////////////////

set the SearchRectangle to "Common/CustomRectangle".ScreenPart("TopHalf")

put EveryImageLocation("Printer/DustbinButton") into DustbinList

put the reverse of DustbinList into DustbinList

repeat with each item of DustbinList
	click it
	wait 1
end repeat

set the SearchRectangle to empty
